version: '3.8'
services:
  web-app:
    container_name: web-app
    image: django_gunicorn_instance # Added in
    # This calls gunicorn to run core.wsgi with the gunicorn-cfg.py configuration file by using the -c (--config) command
    command: gunicorn -c gunicorn-cfg.py core.wsgi --reload
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    # Passes the environment file through for decouple
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - db_network
      - web_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE_ENV}
      - POSTGRES_USER=${SQL_USER_ENV}
      - POSTGRES_PASSWORD=${SQL_PASSWORD_ENV}
    expose:
      # Expose this port to all connections
      - "5432"
    restart: always
    networks:
      # Make sure the webapp and the db has access to the same networks
      - db_network

  redis:
    image: redis:7-alpine
    # Save to disk every 20 seconds
    command: redis-server --save 20 1
    networks:
      # Make sure the redis and the db has access to the same networks
      - db_network
      - web_network
    volumes:
      - cache:/data

  celery_worker:
    # Build off the same docker file as Django, since they share many scripts and Celery tasks use django's ORM
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-app_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      # - ./.env/.dev-sample
      - ./.env
    networks:
      - db_network
      - web_network
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-app_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      # - ./.env/.dev-sample
      - ./.env
    networks:
      - db_network
      - web_network
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-app_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      # - ./.env/.dev-sample
      - ./.env
    ports:
      - 5557:5555
    networks:
      - db_network
      - web_network
    depends_on:
      - redis
      - db

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - web-app

networks:
  db_network:
    driver: bridge # Bridge means there is no network being created
  web_network:
    driver: bridge

volumes:
  postgres_data: # Save on the 'local' volume (I believe like a name)

  cache:
    driver: local
