version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    image: django_gunicorn_instance # Added in
    # This calls gunicorn to run core.wsgi with the gunicorn-cfg.py configuration file by using the -c (--config) command
    command: gunicorn -c gunicorn-cfg.py core.wsgi
    restart: always
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - db_network
      - web_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE_ENV}
      - POSTGRES_USER=${SQL_USER_ENV}
      - POSTGRES_PASSWORD=${SQL_PASSWORD_ENV}
    expose: # Expose this port to all connections
      - "5432"
    restart: always
    networks:
      - db_network

# SQL_HOST_ENV=db
# SQL_PORT_ENV=5432

  redis:
    image: redis:7-alpine

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app

networks:
  db_network:
    driver: bridge # Bridge means there is no network being created
  web_network:
    driver: bridge

volumes:
  postgres_data:
