# Generated by Django 4.2.7 on 2023-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_title', models.CharField(max_length=30)),
                ('image_description', models.CharField()),
                ('main_image', models.ImageField(upload_to='recreation')),
                ('tile_image', models.ImageField(upload_to='recreation')),
            ],
        ),
    ]
