# Generated by Django 4.2.7 on 2023-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
