# Generated by Django 4.2.7 on 2023-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0002_recreation_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_ocean', 'filter_ocean'), ('filter_mountain', 'filter_mountain'), ('filter_misc', 'filter_misc'), ('filter_art', 'filter_art')], default=''),
        ),
    ]
