# Generated by Django 4.2.7 on 2023-11-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0003_recreation_filter_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Stack_Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=30)),
                ('tool_description', models.CharField()),
                ('tool_link', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
                ('main_image', models.ImageField(upload_to='web_stack_icons')),
            ],
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_mountain', 'Mountain'), ('filter_ocean', 'Ocean'), ('filter_art', 'Art'), ('filter_misc', 'Misc')], default=''),
        ),
    ]
