# Generated by Django 4.2.7 on 2023-11-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0004_web_stack_tools_alter_recreation_filter_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSkillCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('category_display', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_ocean', 'Ocean'), ('filter_misc', 'Misc'), ('filter_art', 'Art'), ('filter_mountain', 'Mountain')], default=''),
        ),
        migrations.CreateModel(
            name='ResumeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=30)),
                ('skill_years', models.FloatField(default=0)),
                ('skill_filter_category', models.CharField(max_length=30)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui_testing.resumeskillcategories')),
            ],
        ),
    ]
