# Generated by Django 4.2.7 on 2023-11-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0005_resumeskillcategories_alter_recreation_filter_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExperienceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('still_there', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('category_display', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_art', 'Art'), ('filter_ocean', 'Ocean'), ('filter_mountain', 'Mountain'), ('filter_misc', 'Misc')], default=''),
        ),
        migrations.CreateModel(
            name='ResumeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_item', models.BooleanField()),
                ('line_text', models.TextField()),
                ('line_skill_categories', models.ManyToManyField(to='ui_testing.resumeskills')),
                ('resume_experience_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_testing.resumeexperienceblock')),
            ],
        ),
    ]
