# Generated by Django 4.2.7 on 2023-11-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0006_resumeexperienceblock_resumeexperiencecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeexperiencecategory',
            name='icon_class',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_art', 'Art'), ('filter_ocean', 'Ocean'), ('filter_misc', 'Misc'), ('filter_mountain', 'Mountain')], default=''),
        ),
    ]
