# Generated by Django 4.2.7 on 2023-11-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0009_resumeexperienceblock_sub_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeline',
            name='display_order',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_art', 'Art'), ('filter_mountain', 'Mountain'), ('filter_misc', 'Misc'), ('filter_ocean', 'Ocean')], default=''),
        ),
    ]
