# Generated by Django 4.2.7 on 2023-11-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0010_resumeline_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeexperienceblock',
            name='lines',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_mountain', 'Mountain'), ('filter_ocean', 'Ocean'), ('filter_misc', 'Misc'), ('filter_art', 'Art')], default=''),
        ),
        migrations.AlterField(
            model_name='resumeline',
            name='line_skill_categories',
            field=models.ManyToManyField(blank=True, to='ui_testing.resumeskills'),
        ),
    ]
