# Generated by Django 4.2.7 on 2023-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0011_resumeexperienceblock_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeexperienceblock',
            name='aggregate_line_skills',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='filter_field',
            field=models.CharField(choices=[('filter_ocean', 'Ocean'), ('filter_misc', 'Misc'), ('filter_mountain', 'Mountain'), ('filter_art', 'Art')], default=''),
        ),
    ]
